### ISSUE TITLE
Porting some of rules from original project

### ISSUE THREAD

**Issue by gladykov** [CachyOS/ananicy-rules#116]
Since https://github.com/nefelim4ag/Ananicy/blob/master/ananicy.d/ is archived, would you be open to moving some of rules form there to your project? I'm thinking about only rules which do alter nice/ionice levels, and without creating new mappings (meaning: reusing  your existing mappings from `00-types.types`. I could tackle this in a few category based PRs.

**Comment by ptr1337** [comment]
We have created explicitly a complete own set of rules, because the upstream rules were simply not correctly definied, some processes did just nothing, besides overloading the system.

We do not need to have dozens of processes in and change nothing on then. Keep it limited to the major games and software, instead of filling it with not required stuff.
